### PR TITLE
Add DOA POSIX outbox docs

### PR DESCRIPTION
**Pull request by dtitov**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [x] Documentation change
- [ ] Language translation

### Pull request long description:
Describes these changes: https://github.com/neicnordic/LocalEGA-DOA/pull/22

### CODE REVIEW

**Comment by blankdots** [comment]
would be nice to add some reasoning behind the outbox can it be used for.

**Comment by dtitov** [comment]
Done.

**Review by blankdots — APPROVED** [review]

**Comment by dtitov** [comment]
Hm, I didn't expect the documentation changes to fail the int-tests. Maybe timeout? Restarting the job anyway...

**Comment by dtitov** [comment]
Ok, green now, merging.

**Pull request merged**
